version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app:rw
    networks:
      - proxy
    labels:
      traefik.http.routers.app.rule: Host(`thiagobraga.local`)
      traefik.http.routers.app.entrypoints: https
      traefik.http.routers.app.tls: true
      traefik.http.services.app.loadbalancer.server.port: 5000

networks:
  proxy:
    external: true
