// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjmjgycyharzwygwvcbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqbWpneWN5aGFyend5Z3d2Y2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjEzNTIsImV4cCI6MjA2MjM5NzM1Mn0.jTrEu_fSB4gEIVkqTApliUDmKGgWxfMe55PRVgTmJDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);